name: Build and Deploy
on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Clean Install dependencies and Build
        run: |
          yarn install
          rm -rf __sapper__
          yarn predeploy
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: "__sapper__/export"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./__sapper__/export
