name: Build and Deploy
on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Clean Install dependencies and Build
        run: |
          yarn install
          rm -rf __sapper__
          yarn predeploy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./__sapper__/export
          publish_branch: master

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: __sapper__/export
